Update sparse-checkout.yml

diff --git a/.github/workflows/sparse-checkout.yml b/.github/workflows/sparse-checkout.yml
--- a/.github/workflows/sparse-checkout.yml
+++ b/.github/workflows/sparse-checkout.yml
@@ -12,30 +12,40 @@ jobs:
     runs-on: ubuntu-20.04
 
     steps:
-      - uses: snow-actions/sparse-checkout@v1.1.0
+      - name: Empty path
+        uses: snow-actions/sparse-checkout@v1.1.0
         with:
-          patterns: |
-            docs
-            packer
-          path: sparse
-      - run: |
-          set -x
-          git sparse-checkout list
-          git log
-          ls -la
-        working-directory: sparse
-      - uses: snow-actions/sparse-checkout@v1.1.0
+          path: ''
+      - run: ls -la
+      - name: .
+        uses: snow-actions/sparse-checkout@v1.1.0
         with:
-          repository: snow-actions/tweet
-          patterns: |
-            src
-          path: tweet
-      - run: |
-          set -x
-          git sparse-checkout list
-          git log
-          ls -la
-        working-directory: tweet
+          path: '.'
+      - run: ls -la
+#       - uses: snow-actions/sparse-checkout@v1.1.0
+#         with:
+#           patterns: |
+#             docs
+#             packer
+#           path: sparse
+#       - run: |
+#           set -x
+#           git sparse-checkout list
+#           git log
+#           ls -la
+#         working-directory: sparse
+#       - uses: snow-actions/sparse-checkout@v1.1.0
+#         with:
+#           repository: snow-actions/tweet
+#           patterns: |
+#             src
+#           path: tweet
+#       - run: |
+#           set -x
+#           git sparse-checkout list
+#           git log
+#           ls -la
+#         working-directory: tweet
 #       - uses: snow-actions/sparse-checkout@v1.1.0
 #         with:
 #           repository: SnowCait/github-actions-self-hosted-runner-sandbox
@@ -59,86 +69,86 @@ jobs:
 #       - run: git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +master:refs/remotes/origin/master
 #       - run: git checkout --progress --force -B master refs/remotes/origin/master
 
-  local:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ ubuntu-20.04 ]
-#         os: [ ubuntu-20.04, ubuntu-18.04, windows-2019, windows-2016, macos-10.15 ]
-      fail-fast: false
-    defaults:
-      run:
-        shell: bash
+#   local:
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ ubuntu-20.04 ]
+# #         os: [ ubuntu-20.04, ubuntu-18.04, windows-2019, windows-2016, macos-10.15 ]
+#       fail-fast: false
+#     defaults:
+#       run:
+#         shell: bash
 
-    steps:
-      - name: Checkout .github/sparse-checkout/
-        uses: actions/checkout@v2.3.4
+#     steps:
+#       - name: Checkout .github/sparse-checkout/
+#         uses: actions/checkout@v2.3.4
       
-      - run: which git
-#       - run: $(which mkdir) abc
-#       - run: mkdir def
+#       - run: which git
+# #       - run: $(which mkdir) abc
+# #       - run: mkdir def
 
-      - name: default
-        uses: ./.github/sparse-checkout/
-        with:
-          path: default
-      - run: |
-          set -x
-          git sparse-checkout list
-          git log
-          ls -la
-        working-directory: default
-      - run: |
-          if [ -d docs ]; then
-            exit 1
-          fi
-        working-directory: default
+#       - name: default
+#         uses: ./.github/sparse-checkout/
+#         with:
+#           path: default
+#       - run: |
+#           set -x
+#           git sparse-checkout list
+#           git log
+#           ls -la
+#         working-directory: default
+#       - run: |
+#           if [ -d docs ]; then
+#             exit 1
+#           fi
+#         working-directory: default
 
-      - name: 1st
-        uses: ./.github/sparse-checkout/
-        with:
-          patterns: |
-            docs
-            packer
-          path: twice
-      - run: |
-          set -x
-          git sparse-checkout list
-          git log
-          ls -la
-        working-directory: twice
+#       - name: 1st
+#         uses: ./.github/sparse-checkout/
+#         with:
+#           patterns: |
+#             docs
+#             packer
+#           path: twice
+#       - run: |
+#           set -x
+#           git sparse-checkout list
+#           git log
+#           ls -la
+#         working-directory: twice
 
-#       - name: 2nd
+# #       - name: 2nd
+# #         uses: ./.github/sparse-checkout/
+# #         with:
+# #           patterns: 'docs packer'
+# #           path: twice
+# #       - run: ls -l twice/
+
+#       - name: sha
 #         uses: ./.github/sparse-checkout/
 #         with:
 #           patterns: 'docs packer'
-#           path: twice
-#       - run: ls -l twice/
+#           path: sha
+#           ref: 1068da213d7ecfae787d21630bc0955e31a6659a
+#       - run: ls -l sha/
 
-      - name: sha
-        uses: ./.github/sparse-checkout/
-        with:
-          patterns: 'docs packer'
-          path: sha
-          ref: 1068da213d7ecfae787d21630bc0955e31a6659a
-      - run: ls -l sha/
+#       - name: other repo
+#         uses: ./.github/sparse-checkout/
+#         with:
+#           repository: snow-actions/tweet
+#           patterns: 'src'
+#           path: other
+#           # ref: main
+#       - run: ls -l other/
 
-      - name: other repo
-        uses: ./.github/sparse-checkout/
-        with:
-          repository: snow-actions/tweet
-          patterns: 'src'
-          path: other
-          # ref: main
-      - run: ls -l other/
-
-      - name: private
-        uses: ./.github/sparse-checkout/
-        with:
-          repository: SnowCait/github-actions-self-hosted-runner-sandbox
-          path: private
-          token: ${{ secrets.PAT }}
-      - run: ls -l private/
+#       - name: private
+#         uses: ./.github/sparse-checkout/
+#         with:
+#           repository: SnowCait/github-actions-self-hosted-runner-sandbox
+#           path: private
+#           token: ${{ secrets.PAT }}
+#       - run: ls -l private/
 
 #   gogaille:
 #     runs-on: ubuntu-latest
@@ -165,6 +175,11 @@ jobs:
         uses: actions/checkout@v2
         with:
           path: ''
+      - run: ls -la
+      - name: .
+        uses: actions/checkout@v2
+        with:
+          path: '.'
       - run: ls -la
 
 #       - name: 1st
